import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { existsSync, readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const migrationUrl = new URL('../migrations/20260805_2_rh_onboarding_operacoes.sql', import.meta.url);
const fixtureUrl = new URL('./rh_onboarding_operacoes_fixture.sql', import.meta.url);
const migrationPath = fileURLToPath(migrationUrl);
const fixturePath = fileURLToPath(fixtureUrl);
const database = 'rh_onboarding_fixture';
const container = `rh-onboarding-${process.pid}-${randomUUID().slice(0, 8)}`;
const image = 'postgres:17.10-alpine';

const setupSql = String.raw`
create extension if not exists pgcrypto;
create role anon nologin;
create role authenticated nologin;
create role service_role nologin;
create schema auth;
create function auth.uid() returns uuid language sql stable as $$
  select nullif(current_setting('request.jwt.claim.sub', true), '')::uuid;
$$;
create table public.user_profiles (id uuid primary key, nome text, role text);
create function public.rh_is_admin_or_rh() returns boolean language sql stable as $$
  select auth.uid() is not null;
$$;
create table public.colaboradores (
  id integer generated by default as identity primary key,
  nome varchar not null, nome_completo varchar, tipo varchar not null,
  departamento varchar not null, funcao varchar not null, unidade_fixa varchar,
  is_rateado boolean default false, ativo boolean default true,
  status text default 'active', tipo_contrato text default 'pj',
  salario_base numeric default 0, data_admissao date, cpf text, email text,
  telefone text, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table public.rh_templates (
  id uuid primary key default gen_random_uuid(), tipo_processo text not null,
  nome text not null, ativo boolean not null default true, arquivado_em timestamptz,
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table public.rh_template_etapas (
  id uuid primary key default gen_random_uuid(), template_id uuid not null references public.rh_templates(id) on delete cascade,
  codigo text not null, titulo text not null, categoria text not null, ordem integer not null,
  obrigatoria boolean not null default true, prazo_offset_dias integer,
  responsavel_padrao_papel text, instrucoes text, modelo_mensagem text,
  link_referencia text, link_reuniao text, notificar_responsaveis boolean default true,
  notificar_colaborador boolean default false, metadata_json jsonb default '{}'::jsonb
);
create table public.rh_template_checklist_itens (
  id uuid primary key default gen_random_uuid(), template_etapa_id uuid not null references public.rh_template_etapas(id) on delete cascade,
  titulo text not null, descricao text, link_url text, obrigatorio boolean default true,
  ordem integer not null, metadata_json jsonb default '{}'::jsonb
);
create table public.rh_template_documentos (
  id uuid primary key default gen_random_uuid(), template_id uuid not null references public.rh_templates(id) on delete cascade,
  tipo_documento text not null, obrigatorio boolean default true, ordem integer not null,
  metadata_json jsonb default '{}'::jsonb
);
create table public.rh_candidatos (
  id uuid primary key default gen_random_uuid(), nome text not null, email text,
  telefone text, cpf text, status text not null, aprovado_em timestamptz,
  colaborador_convertido_id integer references public.colaboradores(id),
  created_by uuid not null references public.user_profiles(id),
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table public.rh_processos (
  id uuid primary key default gen_random_uuid(), tipo text not null, status text not null,
  candidato_id uuid references public.rh_candidatos(id) on delete set null,
  colaborador_id integer references public.colaboradores(id) on delete set null,
  template_id uuid references public.rh_templates(id) on delete set null,
  titulo text not null, unidade text, departamento text, cargo text, tipo_vinculo text,
  owner_user_id uuid not null references public.user_profiles(id), mentor_user_id uuid,
  prioridade text default 'media', data_inicio date not null, data_fim_prevista date,
  data_fim_real date, observacoes text, metadata_json jsonb default '{}'::jsonb,
  created_at timestamptz default now(), updated_at timestamptz default now()
);
create table public.rh_processo_participantes (
  id uuid primary key default gen_random_uuid(), processo_id uuid not null references public.rh_processos(id) on delete cascade,
  user_id uuid not null, papel text not null, principal boolean default false
);
create table public.rh_processo_etapas (
  id uuid primary key default gen_random_uuid(), processo_id uuid not null references public.rh_processos(id) on delete cascade,
  template_etapa_id uuid references public.rh_template_etapas(id) on delete set null,
  codigo text not null, titulo text not null, categoria text not null, status text not null,
  ordem integer not null, obrigatoria boolean default true, data_prevista date,
  data_limite date, instrucoes text, modelo_mensagem text, link_referencia text,
  link_reuniao text, notificar_responsaveis boolean default true,
  notificar_colaborador boolean default false, metadata_json jsonb default '{}'::jsonb
);
create table public.rh_checklist_itens (
  id uuid primary key default gen_random_uuid(), etapa_id uuid not null references public.rh_processo_etapas(id) on delete cascade,
  titulo text not null, descricao text, link_url text, obrigatorio boolean default true,
  concluido boolean default false, ordem integer not null, metadata_json jsonb default '{}'::jsonb
);
create table public.rh_etapa_responsaveis (
  id uuid primary key default gen_random_uuid(), etapa_id uuid not null references public.rh_processo_etapas(id) on delete cascade,
  user_id uuid not null, papel text not null, principal boolean default false
);
create table public.rh_documentos (
  id uuid primary key default gen_random_uuid(), processo_id uuid not null references public.rh_processos(id) on delete cascade,
  candidato_id uuid, colaborador_id integer, tipo_documento text not null,
  obrigatorio boolean default true, status text not null, updated_at timestamptz default now()
);
create table public.rh_historico_eventos (
  id uuid primary key default gen_random_uuid(), processo_id uuid not null references public.rh_processos(id) on delete cascade,
  entidade_tipo text not null, entidade_id uuid, acao text not null, para_json jsonb,
  comentario text, actor_user_id uuid not null
);
create table public.tarefas (
  id uuid primary key default gen_random_uuid(), titulo text not null,
  vinculo_tipo text, vinculo_id uuid
);
`;

function docker(args, options = {}) {
  return spawnSync('docker', args, {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
    timeout: 120_000,
    ...options,
  });
}

function requireSuccess(result, label) {
  if (result.error || result.status !== 0) {
    throw new Error([label, result.error?.message, result.stdout, result.stderr].filter(Boolean).join('\n'));
  }
  return result;
}

function psql(sql, label, pgOptions = null) {
  const prefix = ['exec', '-i', container];
  if (pgOptions) prefix.push('env', `PGOPTIONS=${pgOptions}`);
  return requireSuccess(docker([
    ...prefix, 'psql',
    '--username', 'postgres', '--dbname', database,
    '--no-psqlrc', '--set', 'ON_ERROR_STOP=1',
  ], { input: sql }), label);
}

async function waitForPostgres() {
  for (let attempt = 0; attempt < 60; attempt += 1) {
    const finalServer = docker([
      'exec', container, 'sh', '-c', 'test "$(cat /proc/1/comm)" = postgres',
    ]);
    const ready = docker(['exec', container, 'pg_isready', '--username', 'postgres', '--dbname', database]);
    if (finalServer.status === 0 && ready.status === 0) return;
    await new Promise((resolve) => setTimeout(resolve, 500));
  }
  throw new Error('PostgreSQL 17 nao ficou pronto em 30 segundos.');
}

assert.ok(existsSync(migrationPath), `migration ausente: ${migrationPath}`);
assert.ok(existsSync(fixturePath), `fixture ausente: ${fixturePath}`);
requireSuccess(docker(['info', '--format', '{{.ServerVersion}}']), 'Docker daemon indisponivel');

let started = false;
try {
  requireSuccess(docker([
    'run', '--detach', '--rm', '--name', container,
    '--env', 'POSTGRES_PASSWORD=fixture-only',
    '--env', `POSTGRES_DB=${database}`,
    image,
  ]), 'Falha ao criar PostgreSQL efemero');
  started = true;
  await waitForPostgres();

  psql(setupSql, 'Falha ao provisionar schema minimo');
  psql(readFileSync(migrationUrl, 'utf8'), 'Falha ao aplicar migration real');

  const refused = docker([
    'exec', '-i', container, 'psql', '--username', 'postgres', '--dbname', database,
    '--no-psqlrc', '--set', 'ON_ERROR_STOP=1',
  ], { input: readFileSync(fixtureUrl, 'utf8') });
  assert.notEqual(refused.status, 0, 'fixture deveria recusar execucao sem guard local');
  assert.match(`${refused.stdout}\n${refused.stderr}`, /REFUSED: app\.rh_onboarding_fixture_guard/i);

  const result = psql(
    readFileSync(fixtureUrl, 'utf8'),
    'Fixture comportamental RH falhou',
    '-c app.rh_onboarding_fixture_guard=local_ci_only',
  );
  assert.match(result.stdout, /RH_ONBOARDING_FIXTURE_OK/);

  const rollback = psql(String.raw`
    select
      (select count(*) from public.user_profiles)
      + (select count(*) from public.colaboradores)
      + (select count(*) from public.rh_candidatos)
      + (select count(*) from public.rh_processos)
      + (select count(*) from public.tarefas);
  `, 'Falha ao provar rollback');
  assert.match(rollback.stdout, /\n\s*0\s*\n/);

  process.stdout.write('[rh-onboarding-fixture] PostgreSQL 17\n');
  process.stdout.write('[rh-onboarding-fixture] rollback_sentinel_rows=0\n');
  process.stdout.write(result.stdout);
} finally {
  if (started) docker(['rm', '--force', container]);
}
